name: pytorch_rl
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=2.1.4
  - matplotlib=3.1.3
  - notebook=6.0.3
  - numpy=1.18.1
  - opencv=4.3.0
  - pandas=1.0.1
  - pip=20.0.2
  - python=3.7.6
  - pip:
    - atari-py==0.2.6
    - gym==0.17.1
    - opencv-python==4.2.0.34
    - torch==1.5.0
    - tensorboardX==2.0
    
